### ISSUE TITLE
Either remove front end from this repo entirely, or migrate front end back into this repo but use separate dirs with separate package.json's

### ISSUE THREAD

**Issue by pcowgill** [clrfund/monorepo#12]

**Comment by pcowgill** [comment]
Some discussion related to this is happening https://github.com/clr-fund/contracts/issues/10#issuecomment-595843947

**Comment by proofoftom** [comment]
From #10 
> If we want `npm install` or `yarn` at the root to install everything, we could use `lerna`

I'm all for this. A further justification for this is that we'll want to publish the contracts in standalone form for others to implement in their projects. I imagine this'll be the desirable structure for other projects too, so will implement in the [boilerplate](https://github.com/raid-guild/buidler-waffle-typechain-oz-vue) as well.

**Comment by pcowgill** [comment]
I haven't been following this project closely lately, but I'd still be curious for context on why you closed this, @proofoftom. Thanks!

**Comment by proofoftom** [comment]
@pcowgill you'll notice now that the repo is now using yarn workspaces with separate `contracts` and `vue-app` directories, so this issue is considered complete.

**Comment by pcowgill** [comment]
@proofoftom Makes sense, thanks!
