### ISSUE TITLE
Frontend to allow a user to submit a signed verification

### ISSUE THREAD

**Issue by adamstallard** [clrfund/monorepo#135]
This goes beyond the react native component that @samgos [built here](https://github.com/burnsignal/BrightID-EthereumAddressService) that we can use.  It also goes beyond creating the registry smart contract, which is the subject of https://github.com/clrfund/monorepo/issues/26.

We need a frontend piece that:

Allows a user to self-sponsor (see https://github.com/clrfund/monorepo/issues/159 , https://github.com/clrfund/monorepo/issues/136 )

Gets a signed verification from this endpoint (substitute the user's contextid)
https://app.brightid.org/node/v5/verifications/clr.fund/0xdc0046b52e2e38aee2271b6171ebb65ccd337518?signed=eth

Then creates the transaction to allow a user to submit it to a smart contract's verify function [similar to this one.](https://github.com/BrightID/BrightID-SmartContract/blob/master/v4/BrightID.sol#L23-L44)   (This function will be in the registry contract that [implements this interface](https://github.com/clrfund/monorepo/blob/40a3bfc2f2b460107bfa3914d105b73a36d37797/contracts/contracts/verifiedUserRegistry/IVerifiedUserRegistry.sol).)

**Comment by xuhcc** [comment]
I found [this document](https://docs.google.com/document/d/16-gqjfJLz7WSYVDHVQSFKK3Mj0GFWetxdgE9nQuMS9o/) which describes the verfication process. According to it, we need to do the following:

1. Call [`BrightIdUserRegistry.sponsor()`](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L40) with user's address to emit `Sponsor` event.
2. Call `/operations` endpoint on BrightID node to sponsor the user.
3. Generate QR code with a "deep link" and present it to the user.
4. Wait until user approves the request and then get signature data from `/verifications` endpoint.
5. Add user to the registry by calling [`BrightIdUserRegistry.register()`](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L76) and with the signature data.

@adamstallard Is that correct?

Some other questions:
- What should we use as `contextId`? The documentation says that we need to generate a uuid but it looks like we actually need to use ethereum address of the user.
- What's the address of the [verifier](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L89) who produces signed verifications?
- What should we use as a [`_timestamp`](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L79)?

**Comment by adamstallard** [comment]
> I found [this document](https://docs.google.com/document/d/16-gqjfJLz7WSYVDHVQSFKK3Mj0GFWetxdgE9nQuMS9o/) which describes the verfication process. According to it, we need to do the following:
> 
> 1. Call [`BrightIdUserRegistry.sponsor()`](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L40) with user's address to emit `Sponsor` event.
> 2. Call `/operations` endpoint on BrightID node to sponsor the user.
> 3. Generate QR code with a "deep link" and present it to the user.
> 4. Wait until user approves the request and then get signature data from `/verifications` endpoint.
> 5. Add user to the registry by calling [`BrightIdUserRegistry.register()`](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L76) and with the signature data.
> 
> @adamstallard Is that correct?
> 
> Some other questions:
> - What should we use as `contextId`? The documentation says that we need to generate a uuid but it looks like we actually need to use ethereum address of the user.
> - What's the address of the [verifier](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L89) who produces signed verifications?
> - What should we use as a [`_timestamp`](https://github.com/clrfund/monorepo/blob/cc969dcccd3d86fd81def1d3226e987ca5ae8ff4/contracts/contracts/verifiedUserRegistry/BrightIDUserRegistry.sol#L79)?

@xuhcc We either emit a sponsor event or call the `/operations` endpoint. We don't need to do both.
