### ISSUE TITLE
Funding Round Contract: Review and MVP-finalize existing contract

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#14]

**Comment by xuhcc** [comment]
I'm continuing to work on contracts and decided to create a sequence diagram for MVP before changing any code.
[![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgT3duZXJcbiAgICBwYXJ0aWNpcGFudCBQb29sQ29udHJpYnV0b3JcbiAgICBwYXJ0aWNpcGFudCBSZWNpcGllbnRcbiAgICBwYXJ0aWNpcGFudCBGYWN0b3J5XG4gICAgcGFydGljaXBhbnQgQ29udHJpYnV0b3JcbiAgICBwYXJ0aWNpcGFudCBGdW5kaW5nUm91bmRcbiAgICBwYXJ0aWNpcGFudCBNQUNJXG4gICAgcGFydGljaXBhbnQgQ29vcmRpbmF0b3JcbiAgICBcbiAgICBDb29yZGluYXRvciAtLT4-IE93bmVyOiBwcm92aWRlIHB1YmxpYyBrZXlcbiAgICBPd25lciAtPj4gRmFjdG9yeTogZGVwbG95IGZhY3RvcnksIHNldCBjb29yZGluYXRvciwgdG9rZW4gYW5kIG90aGVyIHBhcmFtZXRlcnNcbiAgICBQb29sQ29udHJpYnV0b3IgLT4-IEZhY3Rvcnk6IGRvbmF0ZSB0byB0aGUgbWF0Y2hpbmcgcG9vbFxuXG4gICAgbG9vcCBBZGRpbmcgcmVjaXBpZW50c1xuICAgIFx0UmVjaXBpZW50IC0tPj4gT3duZXI6IGFzayBmb3IgcmVnaXN0cmF0aW9uXG4gICAgXHRPd25lciAtPj4gRmFjdG9yeTogY2FsbCBhZGRSZWNpcGllbnQoKVxuICAgIGVuZFxuICAgIFxuICAgIGxvb3AgRXZlcnkgcm91bmRcbiAgICBcdE93bmVyIC0-PiBGYWN0b3J5OiBjYWxsIGRlcGxveU5ld1JvdW5kKClcbiAgICBcdEZhY3RvcnkgLT4-IEZ1bmRpbmdSb3VuZDogZGVwbG95IEZ1bmRpbmdSb3VuZCBjb250cmFjdFxuICAgIFx0T3duZXIgLT4-IEZhY3Rvcnk6IGNhbGwgZGVwbG95TWFjaSgpXG4gICAgXHRGYWN0b3J5IC0-PiBNQUNJOiBjcmVhdGUgbmV3IE1BQ0kgaW5zdGFuY2Ugd2l0aCBNQUNJIGZhY3RvcnlcbiAgICBcdFxuICAgIFx0bG9vcCBGdW5kaW5nXG4gICAgXHRcdE5vdGUgb3ZlciBDb250cmlidXRvciwgRnVuZGluZ1JvdW5kOiBjb250cmlidXRvciByZWdpc3RlcnMgdGhlaXIgSURcbiAgICBcdFx0Q29udHJpYnV0b3IgLT4-IEZ1bmRpbmdSb3VuZDogZG9uYXRlIHRvIHRoZSBwb29sICggY2FsbCBjb250cmlidXRlKCkgKVxuICAgIFx0XHRGdW5kaW5nUm91bmQgLT4-IE1BQ0k6IGNhbGwgc2lnblVwKClcbiAgICBcdGVuZFxuICAgIFx0XG4gICAgXHRsb29wIFZvdGluZ1xuICAgIFx0XHROb3RlIHJpZ2h0IG9mIENvbnRyaWJ1dG9yOiBjb250cmlidXRvciBjcmVhdGVzIG1lc3NhZ2VcbiAgICBcdFx0Q29udHJpYnV0b3IgLT4-IE1BQ0k6IHZvdGUgKCBjYWxsIHB1Ymxpc2hNZXNzYWdlKCkgKVxuICAgIFx0ZW5kXG5cdFx0XG5cdFx0Tm90ZSBsZWZ0IG9mIENvb3JkaW5hdG9yOiBjb29yZGluYXRvciBnZW5lcmF0ZXMgcHJvb2ZzXG5cdFx0Q29vcmRpbmF0b3IgLT4-IE1BQ0k6IHByb2Nlc3MgbWVzc2FnZXMgKCBjYWxsIGJhdGNoUHJvY2Vzc01lc3NhZ2UoKSApXG5cdCAgICBDb29yZGluYXRvciAtPj4gTUFDSTogdGFsbHkgdm90ZXMgKCBjYWxsIHByb3ZlVm90ZVRhbGx5QmF0Y2goKSApXG5cdCAgICBcblx0ICAgIE93bmVyIC0-PiBGdW5kaW5nUm91bmQ6IGNhbGN1bGF0ZSBhbGxvY2F0aW9uc1xuXHQgICAgRnVuZGluZ1JvdW5kIC0-PiBNQUNJOiByZXRyaWV2ZSB0YWxseSByZXN1bHRzICg_Pz8pXG5cdCAgICBcbiAgICBcdGxvb3AgRGlzdHJpYnV0aW5nXG4gICAgXHRcdFJlY2lwaWVudCAtPj4gRnVuZGluZ1JvdW5kOiBjYWxsIGNsYWltRnVuZHMoKVxuICAgIFx0ZW5kXG4gICAgZW5kIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgT3duZXJcbiAgICBwYXJ0aWNpcGFudCBQb29sQ29udHJpYnV0b3JcbiAgICBwYXJ0aWNpcGFudCBSZWNpcGllbnRcbiAgICBwYXJ0aWNpcGFudCBGYWN0b3J5XG4gICAgcGFydGljaXBhbnQgQ29udHJpYnV0b3JcbiAgICBwYXJ0aWNpcGFudCBGdW5kaW5nUm91bmRcbiAgICBwYXJ0aWNpcGFudCBNQUNJXG4gICAgcGFydGljaXBhbnQgQ29vcmRpbmF0b3JcbiAgICBcbiAgICBDb29yZGluYXRvciAtLT4-IE93bmVyOiBwcm92aWRlIHB1YmxpYyBrZXlcbiAgICBPd25lciAtPj4gRmFjdG9yeTogZGVwbG95IGZhY3RvcnksIHNldCBjb29yZGluYXRvciwgdG9rZW4gYW5kIG90aGVyIHBhcmFtZXRlcnNcbiAgICBQb29sQ29udHJpYnV0b3IgLT4-IEZhY3Rvcnk6IGRvbmF0ZSB0byB0aGUgbWF0Y2hpbmcgcG9vbFxuXG4gICAgbG9vcCBBZGRpbmcgcmVjaXBpZW50c1xuICAgIFx0UmVjaXBpZW50IC0tPj4gT3duZXI6IGFzayBmb3IgcmVnaXN0cmF0aW9uXG4gICAgXHRPd25lciAtPj4gRmFjdG9yeTogY2FsbCBhZGRSZWNpcGllbnQoKVxuICAgIGVuZFxuICAgIFxuICAgIGxvb3AgRXZlcnkgcm91bmRcbiAgICBcdE93bmVyIC0-PiBGYWN0b3J5OiBjYWxsIGRlcGxveU5ld1JvdW5kKClcbiAgICBcdEZhY3RvcnkgLT4-IEZ1bmRpbmdSb3VuZDogZGVwbG95IEZ1bmRpbmdSb3VuZCBjb250cmFjdFxuICAgIFx0T3duZXIgLT4-IEZhY3Rvcnk6IGNhbGwgZGVwbG95TWFjaSgpXG4gICAgXHRGYWN0b3J5IC0-PiBNQUNJOiBjcmVhdGUgbmV3IE1BQ0kgaW5zdGFuY2Ugd2l0aCBNQUNJIGZhY3RvcnlcbiAgICBcdFxuICAgIFx0bG9vcCBGdW5kaW5nXG4gICAgXHRcdE5vdGUgb3ZlciBDb250cmlidXRvciwgRnVuZGluZ1JvdW5kOiBjb250cmlidXRvciByZWdpc3RlcnMgdGhlaXIgSURcbiAgICBcdFx0Q29udHJpYnV0b3IgLT4-IEZ1bmRpbmdSb3VuZDogZG9uYXRlIHRvIHRoZSBwb29sICggY2FsbCBjb250cmlidXRlKCkgKVxuICAgIFx0XHRGdW5kaW5nUm91bmQgLT4-IE1BQ0k6IGNhbGwgc2lnblVwKClcbiAgICBcdGVuZFxuICAgIFx0XG4gICAgXHRsb29wIFZvdGluZ1xuICAgIFx0XHROb3RlIHJpZ2h0IG9mIENvbnRyaWJ1dG9yOiBjb250cmlidXRvciBjcmVhdGVzIG1lc3NhZ2VcbiAgICBcdFx0Q29udHJpYnV0b3IgLT4-IE1BQ0k6IHZvdGUgKCBjYWxsIHB1Ymxpc2hNZXNzYWdlKCkgKVxuICAgIFx0ZW5kXG5cdFx0XG5cdFx0Tm90ZSBsZWZ0IG9mIENvb3JkaW5hdG9yOiBjb29yZGluYXRvciBnZW5lcmF0ZXMgcHJvb2ZzXG5cdFx0Q29vcmRpbmF0b3IgLT4-IE1BQ0k6IHByb2Nlc3MgbWVzc2FnZXMgKCBjYWxsIGJhdGNoUHJvY2Vzc01lc3NhZ2UoKSApXG5cdCAgICBDb29yZGluYXRvciAtPj4gTUFDSTogdGFsbHkgdm90ZXMgKCBjYWxsIHByb3ZlVm90ZVRhbGx5QmF0Y2goKSApXG5cdCAgICBcblx0ICAgIE93bmVyIC0-PiBGdW5kaW5nUm91bmQ6IGNhbGN1bGF0ZSBhbGxvY2F0aW9uc1xuXHQgICAgRnVuZGluZ1JvdW5kIC0-PiBNQUNJOiByZXRyaWV2ZSB0YWxseSByZXN1bHRzICg_Pz8pXG5cdCAgICBcbiAgICBcdGxvb3AgRGlzdHJpYnV0aW5nXG4gICAgXHRcdFJlY2lwaWVudCAtPj4gRnVuZGluZ1JvdW5kOiBjYWxsIGNsYWltRnVuZHMoKVxuICAgIFx0ZW5kXG4gICAgZW5kIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by xuhcc** [comment]
Diagram updated :arrow_up: :
- Added `MACIFactory` entity.
- More details on initial deployment and set up.

**Comment by xuhcc** [comment]
Diagram updated again :arrow_up:
- Clarified the process of distribution of funds.
- More details.
