### ISSUE TITLE
Factory Contract: owner set recipients

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#16]
Owner can set recipients (up to 16 for the MVP)

**Comment by xuhcc** [comment]
We discussed this in telegram and agreed to store recipients' names and addresses in factory contract. In future versions of the product we may leave only addresses there and store everything else offchain (3box and/or IPFS).

It seems that we can now add up to 1024 recipients https://github.com/appliedzkp/maci/issues/62, though 16 probably would be sufficient for MVP.

If there are no objections, I'll go ahead and implement this.
