### ISSUE TITLE
Funding Round Contract: Make upgradeable

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#17]

**Comment by proofoftom** [comment]
I'm thinking that we actually don't want to do this, since this gives too much ability to deploy an upgraded funding round contract to empty out the round or something of the sorts. Maybe we should make funding rounds pause-able with ability to withdraw all funds back to depositors. Not sure how difficult MACI makes this though.

**Comment by auryn-macmillan** [comment]
The reason to make it upgradable is so that there can be a constant receiving address. That way the receiving address can be hardcoded in other apps and protocols that want to contribute to the matching pool.
If this is not the case, there could potentially be a huge coordination cost to upgrading.

**Comment by slgraham** [comment]
This is definitely an important conversation to have, and any decision we make will come with non-trivial trade-offs. So let me try to lay out the trade-off space as I currently see it:

### Desired properties
A. clr.fund is as trust-minimized as possible
B. clr.fund's infrastructure can be improved over time as new technologies are developed
C. Other protocols and apps can contribute to the matching pool easily without sacrificing their own trust-minimization

### Potential upgrade approaches
1. **by hard fork only:** i.e. contracts are not upgradeable and the only way to get new features or improve infrastructure is to fork the state and move to new contracts 
    - _achieves property A and B_
    - _fails property C_ because the receiving address would change with each fork, making life  difficult on protocols and apps that want to contribute to the matching pool. For example, it would be difficult for them to change to the new clr.fund receiving address after a fork without costly coordination (e.g. a governance proposal) or introducing a trusted admin to make the change.

2. **upgradeable contracts:** i.e. the clr.fund core contracts use upgradeability patterns to allow new features to be added without forking the state.
    - _achieves property B_
    - _achieves property C_ by keeping the receiving address constant
    - _imposes significant challenges to property A_ since clr.fund contract admin rights have to be placed behind some level of governance layer (as simple as a multisig to as complex as tokenized governance).

3. **hard forks with ENS:** same as (1) but using an ENS name to keep the receiving destination constant. When upgrading / forking to new clr.fund contracts, we update the receiving address that our ENS name resolves to.
    - _achieves property B and C_
    - _largely achieves property A_ since the only incremental trust component is for the ENS name to address mapping. Could add an execution delay on the ENS mapping change to minimize attack vector.

4. **upgradability with governance delays:** same as (2) but adds an execution delay so that any contract upgrades don't go into effect for a given period (say, 2 rounds). Any attack on this vector could be avoided by moving incoming fund streams away from the compromised contract before the change goes into effect.
    - _achieves property B and C_
    - _somewhat achieves property A_. Protects against attacks, but the governance footprint is still large 

Personally, I think I'm leaning towards (3) since it keeps upgrades cleanly defined as forks and only adds a small governance footprint to achieve a constant receiving address. What do others think? Are there any other potential approaches?

**Comment by slgraham** [comment]
The above comment is relevant for a decision about the longer term upgradeability of clr.fund. In the shorter term, e.g. for the alpha / round 0, trust-minimization is less important so there's more room for direct contract upgradeability

**Comment by xuhcc** [comment]
Upgradable contracts == more complexity, more bugs, bigger attack surface. I'd prefer immutable contracts (like Uniswap) until (C) becomes relevant (that is when someone actually wants to make an integration). Then we can re-evaluate the options.

**Comment by auryn-macmillan** [comment]
Closing this issue because it has gone stale.
