### ISSUE TITLE
Funding Round Contract: public fund-claiming

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#19]
Anybody can claim funds on behalf of a given recipient

**Comment by xuhcc** [comment]
We found that it's not currently possible to know and verify both the amount of voice credits spent on a vote option and the quadratic vote tally for that option.

https://hackmd.io/NKohKwKgQyeyeQLpLepKig

**Comment by xuhcc** [comment]
We'll also need a way to verify the sum of tally results across all vote options. This number will be used to calculate the proportion of the matching pool that recipient can claim: `matchingPoolShare = quadVoteTallyResult / quadVoteTotalSum`.
