### ISSUE TITLE
Allow contributions to the matching pool

### ISSUE THREAD

**Issue by xuhcc** [clrfund/monorepo#240]
For example, we can add a "project" to the list named "Round N matching pool" and allow users to contribute to it.

Related to #230

**Comment by auryn-macmillan** [comment]
If we're talking about contributions to the matching pool of future rounds, I think your UX makes sense.
But if we're talking about contributing to this round, I think a distinct UI element / page might be a better solution.

For example, perhaps there could be a "contribute" that is displayed when you hover over the matching pool box in the stats at the top. Clicking that might open a modal for contributing to the matching pool.

![image](https://user-images.githubusercontent.com/8453294/102690273-34d14680-41d2-11eb-9c85-c033e25130e9.png)

I'd also be keen to hear Marko's input on the best UX for this.

**Comment by markoprljic** [comment]
I'd rather not hide the button on hover, instead show a small button (or a link) below the Matching pool. 

![Uploading Image 2020-12-19 at 2.36.10 pm.png…]()

**Comment by xuhcc** [comment]
Can we use an icon instead of "contribute" word? Maybe a "plus" sign?

Or we may redesign the whole bottom row of stats block, like this:

![Untitled](https://user-images.githubusercontent.com/1660460/102696204-9da1d880-423d-11eb-97d9-0123a936a490.png)

**Comment by markoprljic** [comment]
Indeed, an allocation bar would be good!

**Comment by xuhcc** [comment]
The UI needs to tell user where the contribution goes:
- Current funding round if it is still running.
- Next funding round if the current one is finished.

**Comment by markoprljic** [comment]
> The UI needs to tell user where the contribution goes:
> 
> * Current funding round if it is still running.
> * Next funding round if the current one is finished.

You mean this should be displayed as an info box, or a notice? Or do you mean that user should be informed about this when completing the transaction?

**Comment by markoprljic** [comment]
I think this information can be added into the cart, when user add a project in cart somewhere we can put that notice, or when initiating te transaction.

**Comment by xuhcc** [comment]
>You mean this should be displayed as an info box, or a notice? Or do you mean that user should be informed about this when completing the transaction?

It should be communicated before user sends funds.

>I think this information can be added into the cart, when user add a project in cart somewhere we can put that notice, or when initiating te transaction.

Yes, we can show a notice when initiating the transaction. Or the button itself could contain the text "contribute to the current round" / "contribute to the next round"

**Comment by markoprljic** [comment]
> Can we use an icon instead of "contribute" word? Maybe a "plus" sign?
> 
> Or we may redesign the whole bottom row of stats block, like this:
> 
> ![Untitled](https://user-images.githubusercontent.com/1660460/102696204-9da1d880-423d-11eb-97d9-0123a936a490.png)

UI update:

- wider main section
- redesigned top part, added funds allocation bar
- Cart will be a right-hand side drawer accessed from the cart button next to the username
- added notifications icon to allow for various system notifications we might need

Option 1
<img width="1427" alt="Image 2020-12-23 at 2 15 50 pm" src="https://user-images.githubusercontent.com/5704285/102999615-a3433b00-4529-11eb-90e3-f783ace5d218.png">

Option 2 (preferred)
<img width="1424" alt="Image 2020-12-23 at 3 00 00 pm" src="https://user-images.githubusercontent.com/5704285/103002677-99243b00-452f-11eb-874d-f2bf55fb7c5c.png">

**Comment by xuhcc** [comment]
Cool! I really like how round stats block looks in Option 2.
Though I'd prefer the cart to be always open.

**Comment by markoprljic** [comment]
Thanks Kiril.

I'm not seeing a problem having cart open when items dropped, closed while
browsing, opened when completing the contribution.

That's a common interaction pattern.

**Comment by xuhcc** [comment]
I created an issue for round stats redesign: #255.

This issue will track progress of matching pool contribution UI that will be implemented separately.

**Comment by xuhcc** [comment]
For now I just added a small button from "Option 2" mockup:

![Screenshot_2020-12-29 clr fund - Projects](https://user-images.githubusercontent.com/1660460/103292598-3800d980-49ff-11eb-92e0-e714366e0e1c.png)
