### ISSUE TITLE
Round stats block

### ISSUE THREAD

**Issue by xuhcc** [clrfund/monorepo#255]
https://github.com/clrfund/monorepo/issues/240#issuecomment-750312962

**Comment by markoprljic** [comment]
UI **Iteration #1** update:

- new Stats bar
- Cart now opens when the user adds a project and when clicking the cart icon
- Notifications panel added (optional if/when needed)

[Try it yourself here.](https://www.figma.com/proto/HotZCx3zNptdm0wCzXtZKf/clr.fund?node-id=964%3A86&viewport=-2618%2C388%2C0.4560229182243347&scaling=min-zoom)

@auryn-macmillan @xuhcc

**Comment by xuhcc** [comment]
I like the "time left to contribute" widget you added here. It makes it easier to understand time constraints.
But in my opinion "Option 2" from your previous post looks better overall.

**Comment by xuhcc** [comment]
Another idea

![Artboard 2 Copy 3](https://user-images.githubusercontent.com/1660460/103377811-7971b180-4af1-11eb-86f4-f638dc8e378d.png)

**Comment by markoprljic** [comment]
I had exactly the same version with bar at the top but dismissed it.

**Comment by markoprljic** [comment]
Left some comments in Figma.

**Comment by xuhcc** [comment]
Latest UI includes search bar: https://ipfs.io/ipfs/Qmdfv35PW7yo9uRQWz1w17TBv7KeDUX4NbJVAhVfn86aCf/
That could influence our design choice here.

At some point we will also add sorting to the project list (maybe there will be a dropdown menu).

**Comment by markoprljic** [comment]
> Latest UI includes search bar: https://ipfs.io/ipfs/Qmdfv35PW7yo9uRQWz1w17TBv7KeDUX4NbJVAhVfn86aCf/
> That could influence our design choice here.
> 
> At some point we will also add sorting to the project list (maybe there will be a dropdown menu).

We had the search bar in earlier versions of the UI (in Figma). I added it back now at the top. Clickin on the icon should show and put the input in focus. 

<img width="715" alt="Image 2021-01-02 at 11 39 32 pm" src="https://user-images.githubusercontent.com/5704285/103467880-cd7bd080-4d53-11eb-96ad-5cb44806b983.png">

**Comment by xuhcc** [comment]
The search bar allows user to search for projects in the project list. We don't need it in the header / on every page.

**Comment by auryn-macmillan** [comment]
Nevertheless, I still think the search bar would make more sense in the header / alongside the page title.
It doesn't have to be visible on every page, only where/when it is relevant.

**Comment by xuhcc** [comment]
Elements that depend on each other should be grouped together unless there is a good reason to place them apart. The search box works only for project list so it is natural to put the search box right above it, where the user expects it to be. I don't see any good reason for placing it in some other place (like user area as suggested above).
In addition, future versions of UI will provide more tools for manipulating the project list, probably filtering (#261) and sorting (#262). It doesn't make any sense to separate these tools from the search bar, and the user area is wrong place for them. I think the most intuitive and familiar arrangement would be a single toolbar with a search box and dropdown menus right above the project list:

![Screenshot_2021-01-03 clr fund - Projects](https://user-images.githubusercontent.com/1660460/103479174-eed4cf00-4ddc-11eb-8300-96c2c36bbec9.png)

**Comment by markoprljic** [comment]
What @xuhcc says is correct. However, we should consider the implementation of the search in multiple phases.
Search should be globally accessible as well if we plan to use it for other areas of the site in the future. 

Phase 1 - search and filter/sort only projects
Phase 2 - global search with categorized results

Search can be implemented as elastic search, or a separate page that opens search functionality (including results), a dropdown elastic search with categorized results (see Gitcoin) or in other ways.

What I'm seeing is that we just have to decide which approach we take and how soon do we expect to include a global search.
Filtering on Projects can always live outside the actual search because it's connected to the projects list allowing users to filter projects without starting a search.

**Comment by xuhcc** [comment]
@markoprljic What do you mean by global search? Should it search for something other than projects?
At some point we may decide to add search to the round list (to quickly find a round by its number). But I don't know what else our users could be interested in.

>search with categorized results (see Gitcoin)

clrfund will not support Gitcoin-like project categories in the foreseeable future. The recommended way of splitting matching funds is to deploy separate clrfund instances with different recipient selection criteria.

**Comment by auryn-macmillan** [comment]
Ok, I'm convinced that @xuhcc's approach is the correct one.

**Comment by xuhcc** [comment]
I've implemented the stats block according to the latest mockup (https://www.figma.com/file/HotZCx3zNptdm0wCzXtZKf/clr.fund?node-id=964%3A86) and made some changes to it:
- Replaced 'total' with 'contributions' (more useful metric).
- Combined 'contributions' and 'contributors' into a single block (so there is even number of blocks).
- Adapted design to different screen sizes.

<img src="https://user-images.githubusercontent.com/1660460/106904167-e3daca80-670b-11eb-84af-44a502c739d7.png" width="800">
<img src="https://user-images.githubusercontent.com/1660460/106904182-e89f7e80-670b-11eb-860c-8b272cdf791d.png" width="500">
<img src="https://user-images.githubusercontent.com/1660460/106904188-eb01d880-670b-11eb-8ea9-f47e5191fa86.png" height="250">

**Comment by auryn-macmillan** [comment]
Looks great!
