### ISSUE TITLE
Port our contracts to run on Optimisim

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#260]
[Optimism](https://optimism.io) is one of the =rollup options we are exploring. Their mainnet is scheduled to launch March 15th, 2020 (according to [this post](https://medium.com/ethereum-optimism/optimism-year-in-review-6624dbba266c?source=collection_home---6------0-----------------------)).Prior to then, we should try out our contracts to see if we need to make any changes.

@xuhcc already identified that we would need to change block.number to block.timestamp, but there may be other issues as well.

Here is a guide to porting contracts to Optimism.
https://hackmd.io/@scopelift/Hy853dTsP

And here is a guide to setting up a local environment for optimism.
https://github.com/ethereum-optimism/optimism-integration

**Comment by xuhcc** [comment]
Looks complicated. Arbitrum provides a much better developer experience, I wonder why there's such a dramatic difference between these L2 solutions.

**Comment by auryn-macmillan** [comment]
I'm not sure, honestly. I agree that Arbitrum's developer experience is currently better, but I think it's worthwhile playing with both as we're not sure which will be production ready first and which will gain more traction / be a better fit for us.

**Comment by auryn-macmillan** [comment]
I'm going to go ahead and close this because it looks like we'll use Arbitrum for the time being.
