### ISSUE TITLE
Automate public function calls with Gelato

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#265]
[Gelato](https://gelato.network/) is a tool for automating smart contract execution on Ethereum. clr.fund has several public function calls that could be executed automatically via Gelato, eliminating the need to for a user to do it manually.

**Comment by xuhcc** [comment]
>clr.fund has several public function calls that could be executed automatically

Can you elaborate? I don't think we need to automate anything.

In general, please do not use issue tracker to advertise projects. The issue should describe a problem that needs solving, not the solution that needs a problem.

**Comment by auryn-macmillan** [comment]
> In general, please do not use issue tracker to advertise projects. The issue should describe a problem that needs solving, not the solution that needs a problem.

Certainly not intending to advertise projects, simply pointing out the projects/technologies that I think are the best current solutions to the issue. Nevertheless, I'll avoid putting project names in the titles in future, unless we've already decided on using the tech.

> Can you elaborate? I don't think we need to automate anything.
I may have jumped the gun a little on this one. Looking through the contracts, the only thing that we could realistically automate would be `claimFunds()`. But I don't think there is enough benefit to warrant the effort.

**Comment by xuhcc** [comment]
Automating actions like `claimFunds()` would mean that we pay for execution, but I think it's better if recipients pay it themselves. (Another similar action is `registerRecipient()` in registry.)
