### ISSUE TITLE
Provide better tools for coordinator

### ISSUE THREAD

**Issue by xuhcc** [clrfund/monorepo#267]
Update [tally.ts](https://github.com/clrfund/monorepo/blob/develop/contracts/scripts/tally.ts) script to work with public networks like rinkeby and xdai.
The script should do the following:
- Read required options from hardhat config.
- Download trusted setup files.
- Automatically process messages and tally the votes.
- Calculate IPFS hash of the tally file and write it to funding round contract.

**Comment by xuhcc** [comment]
Related: https://github.com/appliedzkp/maci/issues/197

**Comment by xuhcc** [comment]
TODO:
- Add script for quick tally (without generating proofs), add script for verifying tally file (requires https://github.com/appliedzkp/maci/pull/205).
- Add a script for key pair generation.
- Do not ask for eth private key (requires migration of maci-cli to ethers v5).

**Comment by samajammin** [comment]
This would be amazing 😍

**Comment by xuhcc** [comment]
It would be nice to use `Wallet` object from hardhat config and set a correct default for `snarkParamsPath` config parameter, but it's not currently feasible.
