### ISSUE TITLE
Deploy an ETHDenver branded instance of clr.fund

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#268]
## To do
- [ ] Wrap xDai when contributing to the round #195 
- [ ] Wrap xDai when contributing to the matching pool
- [x] Change branding to ETHDenver's branding
- [x] Write and deploy SPORK contract (WETH fork with no `withdraw()` function, xDai is forwarded to ETHDenver's wallet)
- [x] Deploy owner contract (Gnosis Safe)
- [x] Deploy factory contract
- [x] Deploy simple user registry
- [x] Deploy simple recipient registry
- [x] Deploy an instance of the UI
- [ ] Write script to bulk add recipients
- [x] Write script to bulk add users
- [x] Write script to that outputs the results in a human readable format quickly (in less than 30 minutes)

---

We need an ETHDenver branded instance of the clr.fund frontend.

The funding round will be relatively short, likely only a few hours, followed by presentations shortly after. So we need to be quick about:
1. adding all of the teams
2. finalizing the round
3. publishing the results

Any things that we can do to help speed those processes will help things to run much more smoothly.

**Comment by auryn-macmillan** [comment]
Started a new branch `ethdenver`

**Comment by xuhcc** [comment]
>If possible, we should point to each of instances from the left menu.

The easiest way to do that is to register two domain names (like `open.ethdenver.eth` and `impact.ethdenver.eth`) and point them to corresponding UI deployments.

**Comment by auryn-macmillan** [comment]
Thanks! That's a great point.

Unfortunately, if we can't find a way to at least informally tally the results (i.e. know the results without the zk-proof) more quickly (in minutes, rather than hours), it's probably not going to be viable for the main prizepools at ETHDenver.

I spoke with them about it already and the suggested that perhaps we use clr.fund to award a bonus prize that via community input. This way it wouldn't matter if it takes hours or days to compute the results.

Another plus to this is that it would mean that there is probably only need for one additional instance of clr.fund, which is less for us to prepare and administrate.

**Comment by auryn-macmillan** [comment]
@proofoftom, I've updated the description with a todo list. We create issues linked to this issue if we want to get more granular. Let me know if any of this is unclear.

@xuhcc, can you help with the last 3 items on the list?

**Comment by xuhcc** [comment]
>@xuhcc, can you help with the last 3 items on the list?

Probably not, I'm busy with other things right now.

**Comment by auryn-macmillan** [comment]
Updated the UI with ETHDenver branding and a new about section.
Preview here: https://gateway.pinata.cloud/ipfs/QmfSoy14NsspEzvUZL3GDHfvHUbscR2iB7i4upmpuZFeEj/#/

**Comment by auryn-macmillan** [comment]
Owner multisig is `0xEeb63C15D4867b6d59F1f504461E38805532A6E5` on xDai.

**Comment by xuhcc** [comment]
@auryn-macmillan What xDai JSON-RPC node you are planning to use?
It could make sense to buy access to dedicated node instead of relying on public node like https://xdai.poanetwork.dev as it can be unreliable (this happened several times in the past). On our main clrfund instance it's not a big issue because funding rounds are long and users can just come again later. But ETHDenver round will be quite short so an outage could ruin it.

**Comment by auryn-macmillan** [comment]
Great point!

I've been using the public xDai nodes. But you're right, an poorly timed outage would rek the event, so it's probably worth setting up a Quiknode account for this. (unless you have another suggestion on a node provider).

**Comment by auryn-macmillan** [comment]
Round is complete :smile:
