### ISSUE TITLE
Mobile / Status.im compatibility

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#275]
The UI is currently pretty broken on status :cry:

In this screenshot the user is already connected to xDai, yet it prompts to reconnect. Also, the styling seems quite broken (although this may be because some data is not loading because xDai is not connected)

![image](https://user-images.githubusercontent.com/8453294/106017427-70dbaf00-608e-11eb-8829-8992a1940efa.png)

**Comment by xuhcc** [comment]
>the styling seems quite broken

@auryn-macmillan Could you try this https://ipfs.io/ipfs/QmTooM6BTrjaC69jBwPEMqEwjje9tF1B41d6bZbKHQKHiN/ ?

>the user is already connected to xDai, yet it prompts to reconnect

I'm not sure it's our fault. Does Status provide standard Ethereum Javascript API?

**Comment by auryn-macmillan** [comment]
This version appears to be working as expected.

I couldn't test contributing though because the round is currently tallying.

**Comment by xuhcc** [comment]
>I couldn't test contributing though because the round is currently tallying.

@auryn-macmillan I started a new round https://ipfs.io/ipfs/QmduvxPi1aMntzKukGJMEjkaUHfaDacn9TzLrs22JRuVm7/

**Comment by auryn-macmillan** [comment]
Seems to work as expected 😊

**Comment by auryn-macmillan** [comment]
Seems to work as expected 😊

![Screenshot_20210205-101753](https://user-images.githubusercontent.com/8453294/107052645-e97ff100-679b-11eb-9622-d589bafbd7eb.jpg)

**Comment by xuhcc** [comment]
Excellent, let's close this issue then.
