### ISSUE TITLE
Deploy clrfund to Optimism testnet

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#293]
With the goal of surfacing compatibility issues or any other issues:

1. Deploy clr.fund to the Optimism testnet 
2. Run a test round
3. Measure gas costs for (1) and (2)

**Comment by slgraham** [comment]
Marked as a `good first issue` because this will be a good way for a new technical contributor to learn how clr.fund works.

**Comment by xuhcc** [comment]
Seems to be a duplicate of #260
