### ISSUE TITLE
Signing key management

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#30]
Users need a way to store their MACI message-signing keys

3box? Ceramic?

**Comment by xuhcc** [comment]
We can simply keep the encrypted EdDSA keys in local storage of the browser. Keys can be discarded when the funding round ends.

3box option is interesting but it is needed only if there are users who access dapp from multiple devices.

**Comment by auryn-macmillan** [comment]
@xuhcc for milestone 3, I assume we're just rolling with the current local storage solution?

**Comment by xuhcc** [comment]
@auryn-macmillan Yes, for now we will store the encrypted key in local storage. The dapp asks user to sign a message at log in. This signature is then used to create a secret key which encrypts the data using AES.

I'll publish the code soon for review.
