### ISSUE TITLE
Errors running tally:local script

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#300]
Hey folks!

I'm trying to simulate a funding round in my local environment (similar to #85).

I followed the [development instructions in your README](https://github.com/clrfund/monorepo#development) & was able to get the app running, import a contributor account in MetaMask, then contribute & reallocate funds.

I'm stuck on the tally step. I read through the [contracts README](https://github.com/clrfund/monorepo/tree/develop/contracts) & tried to follow along but either (most likely) made a user error or something is missing with the instructions.

Here's the error I receive (running this after `votingDeadline` has passed):
```
~/code/ef/forks/monorepo/contracts « git:(develop)
$ yarn tally:local
yarn run v1.19.1
$ hardhat run --network localhost scripts/tally.ts
Error: unable to compute batch update state tree witness data
Error: ENOENT: no such file or directory, open '/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/params/1615336804186.input.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at /Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/ts/index.ts:171:8
    at step (/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/build/index.js:33:23)
    at Object.next (/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/build/index.js:14:53)
    at /Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/build/index.js:4:12)
    at genProofAndPublicSignals (/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/build/index.js:164:12)
    at Object.genBatchUstProofAndPublicSignals (/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/ts/index.ts:111:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/samrichards/code/ef/forks/monorepo/node_modules/maci-circuits/params/1615336804186.input.json'
}
Error: message processing failed
    at main (/Users/samrichards/code/ef/forks/monorepo/contracts/scripts/tally.ts:32:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've tried going through the [Working with ZK proofs step](https://github.com/clrfund/monorepo/tree/develop/contracts#working-with-zk-proofs) & installed zkutil (is that a necessary step to run this script?) but I'm not sure how to "download zkSNARK parameters for 'test' circuits". I started up an ipfs node via `ipfs daemon` & ran the example command but it just hangs (for over an hour):
```
~/code/ef/forks/monorepo/contracts « git:(develop)
$ ipfs get --output snark-params QmeBhtC46dXSEXaemgiAjzpzTxH6FykXDgnTdvHujjPaAR

```

Any clarification on how to properly run the `tally:local` (and then `finalize:local` & `claim:local`) scripts would be greatly appreciated!

**Comment by xuhcc** [comment]
>I've tried going through the Working with ZK proofs step & installed zkutil (is that a necessary step to run this script?) but I'm not sure how to "download zkSNARK parameters for 'test' circuits". I started up an ipfs node via ipfs daemon & ran the example command but it just hangs (for over an hour):

Yes, zkSNARK parameters are required to run the `tally` script. You can also download them from https://gateway.pinata.cloud/ipfs/QmeBhtC46dXSEXaemgiAjzpzTxH6FykXDgnTdvHujjPaAR, just open the link in your browser. Local IPFS node is not necessary, but it should be able to find content too (you could try to download a smaller file to see if it works, e.g. `QmRA3NWM82ZGynMbYzAgYTSXCVM14Wx1RZ8fKP42G6gjgj`, the Bitcoin whitepaper).

**Comment by samajammin** [comment]
Thanks for the response @xuhcc! A couple of clarifying questions...

So once I download them from the link you provided (still waiting for it to load for >1 hour now), I add that as a file within the `monorepo/contracts/snark-params/` directory? Does it matter what the filename is?

Then the README mentions "Set the path to downloaded parameter files":
```
export NODE_CONFIG='{"snarkParamsPath": "../../../contracts/snark-params/", "zkutil_bin": "/usr/bin/zkutil"}'
```
Where am I supposed to run that? In my terminal from the `monorepo/contracts/` directory?

**Comment by xuhcc** [comment]
>So once I download them from the link you provided (still waiting for it to load for >1 hour now), I add that as a file within the monorepo/contracts/snark-params/ directory? Does it matter what the filename is?

`QmeBhtC46dXSEXaemgiAjzpzTxH6FykXDgnTdvHujjPaAR` is IPFS directory that contains several files. You need to download all of them to `monorepo/contracts/snark-params/`. Yes, filenames do matter.

>Then the README mentions "Set the path to downloaded parameter files":

`snarkParamsPath` can be absolute path to `monorepo/contracts/snark-params/` directory, or it can be relative path to MACI CLI executable (`monorepo/node_modules/maci-cli/build/index.js` if I remember it correctly).

If you're running `yarn tally:local` from `monorepo/contracts/` directory, the `../../../contracts/snark-params/` path should work.

`zkutil_bin` should be absolute path to `zkutil` binary. I think you can omit it if you installed `zkutil` according to [instructions in MACI repo](https://github.com/appliedzkp/maci#get-started).
