### ISSUE TITLE
Coordinator Interface

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#31]
Some kind of interface allowing the coordinator to...

- Generate MACI constructor parameters
- deploy MACI
- run zk-snark
- submit results on-chain

**Comment by weijiekoh** [comment]
Hi! Please check out https://github.com/barryWhiteHat/maci/tree/master/cli which provides a command-line interface for the coordinator and users.

**Comment by xuhcc** [comment]
The MACI CLI can now be installed from npm: https://www.npmjs.com/package/maci-cli
We also created our own script for doing the vote tally in local environment (#81).
