### ISSUE TITLE
View previous contributions

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#32]
Contributor can see their previous contributions within a round

View can see recipient contribution totals from previous rounds

**Comment by xuhcc** [comment]
>can see recipient contribution totals from previous rounds

Implemented along with #25  

>Contributor can see their previous contributions within a round

Already done (cart remains open throughout the round).

But we also show cart from previous round when user navigates to it (#25). This allows users to see their past contributions. Possible improvements:

- Do not save every change to local storage after contributing. Only update saved cart when user actually reallocates funds.
- Do not allow to change cart after the end of the round.
