### ISSUE TITLE
Upgrade to Vue 3

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#329]
Hey folks (primarily @xuhcc) - I totally understand if this isn't a priority but I've been learning Vue as part of working in this repo & wondering if it's on your roadmap to upgrade Vue to v3. If not, would you be open to a PR to upgrade it?

**Comment by xuhcc** [comment]
It's not currently on the roadmap, but I think it would be nice to migrate. PRs are welcome :)

**Comment by auryn-macmillan** [comment]
@samajammin if we were to upgrade to Vue 3, how would that impact your team's existing work?

**Comment by johnson86tw** [comment]
Hello👋, I'm willing to tackle this migration from Vue 2 to Vue 3. I have to confirm if this is still needed in the future or being 
addressed elsewhere, so it would be better for me to start working on it.

**Comment by yuetloo** [comment]
closed by #598
