### ISSUE TITLE
Revise current round contributions

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#33]
Allow contributors to revise (increase or decrease) their contributions in the current round

**Comment by xuhcc** [comment]
UI should work like this:
- Don't clear the cart after voting.
- Keep the EdDSA key (#30).
- The user should be able to add/remove projects and change amounts (using sliders?).
- 'Contribute' button becomes inactive if the total sum of contributions changes.

**Comment by xuhcc** [comment]
>I don't think we need sliders, right? Users can just enter the values they want to contribute.

Yes, there will be just regular text inputs (I'm working on it right now). We can implement sliders later.

>It should only be inactive if the total is more than what has been contributed, right? If it's less, the remainder should just get allocated as matching funds.

Correct.
