### ISSUE TITLE
Deploying to a testnet

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#337]
I'm trying to deploy the project to a testnet (Rinkeby) & hitting a couple issues.

### How do I pass in env variables to the Hardhat config?

Here we use `process.env.ETHEREUM_JSONRPC_HTTP_URL`:
https://github.com/clrfund/monorepo/blob/develop/contracts/hardhat.config.ts#L25

I tried creating a `.env` file in /contracts/.env, as well as in the root directory.

.env file contents:
```
ETHEREUM_JSONRPC_HTTP_URL=https://eth-rinkeby.alchemyapi.io/v2/MY_ALECHEMY_API_KEY
```

Yet in hardhat.config.ts, `process.env.ETHEREUM_JSONRPC_HTTP_URL` is undefined. Is there something we need to do in order to import this correctly?

### Gas limit requirement?

Then I tried hard coding the variables into the config for now, so my config looks like:
```
    rinkeby: {
      url: ETHEREUM_JSONRPC_HTTP_URL,
      accounts: [`0x${ROPSTEN_PRIVATE_KEY}`],
    },
```

But running a deploy script:
```
yarn clean && yarn build && hardhat run --network rinkeby scripts/deploy.ts
```

Yields this ethers.js error about gas limits:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000}, method="estimateGas", transaction={"from":"0x4478A591B28042a4Ae39AF955c4C953d4Daee7D2","to":"0xE15fb47b44D8bCdc7A58DF25654Dd874F69CFc7B","data":"0xf6a4a5aa000000000000000000000000e5200e1eb2f89eead3008179281e94fcf9e5fc2f"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.0.17)
    at Logger.makeError (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at checkError (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:68:16)
    at EthersProviderWrapper.<anonymous> (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:463:20)
    at step (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
    at Object.throw (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
    at rejected (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted
      at HttpProvider.request (/Users/samrichards/code/ef/clrfund/contracts/node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
      at LocalAccountsProvider.request (/Users/samrichards/code/ef/clrfund/contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:131:34)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at EthersProviderWrapper.send (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20),
  method: 'estimateGas',
  transaction: {
    from: '0x4478A591B28042a4Ae39AF955c4C953d4Daee7D2',
    to: '0xE15fb47b44D8bCdc7A58DF25654Dd874F69CFc7B',
    data: '0xf6a4a5aa000000000000000000000000e5200e1eb2f89eead3008179281e94fcf9e5fc2f'
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Found this [ethers issue](https://github.com/ethers-io/ethers.js/issues/1232) but doesn't seem to be the case. My [deployer address has Rinkeby funds](https://rinkeby.etherscan.io/address/0x4478A591B28042a4Ae39AF955c4C953d4Daee7D2) & I've confirmed the deployer in scripts/deploy.ts is in fact the correct address.

Have you encountered this before? Could you explain how you deploy the smart contracts to a testnet? I'd be happy to help document this 😄  - thanks in advance!

**Comment by samajammin** [comment]
Oh interesting - it does appear like there's been successful deployment txs on my address:
https://rinkeby.etherscan.io/address/0x4478A591B28042a4Ae39AF955c4C953d4Daee7D2

Is ethers.js just throwing errors despite successful deploys?

**Comment by auryn-macmillan** [comment]
> How do I pass in env variables to the Hardhat config?

Either `export ETHEREUM_JSONRPC_HTTP_URL="https://eth-rinkeby.alchemyapi.io/v2/MY_ALECHEMY_API_KEY"` in your shell or just replace `process.env.ETHEREUM_JSONRPC_HTTP_URL` in hardhat.config.ts.

That said, it would probably be good for us to add dotenv as a dependency and then import it from a gitignored .env file in the contracts directory.

**Comment by samajammin** [comment]
Looking at my Alchemy node it does look like something about the gas estimation requests are failing:
![Image 2021-04-12 at 7 08 03 PM](https://user-images.githubusercontent.com/8097623/114486317-81e28980-9bc2-11eb-8069-b38e830f9137.jpg)

**Comment by xuhcc** [comment]
@samajammin

>Have you encountered this before? Could you explain how you deploy the smart contracts to a testnet? I'd be happy to help 
document this smile - thanks in advance!

It's already documented: https://github.com/clrfund/monorepo/blob/develop/docs/admin.md

>Is ethers.js just throwing errors despite successful deploys?

No, the deployment process was not completed.

I don't know why `script/deploy.ts` is not working, the error is not descriptive. You can try to add console.log statements to find which transaction is failing.

**Comment by samajammin** [comment]
Thanks @xuhcc. I just tried walking through the steps here:
 https://github.com/clrfund/monorepo/blob/develop/docs/admin.md

(I ran this on the Rinkeby testnet: `yarn hardhat console --network rinkeby`)

I hit an error on this step:
```
> const maciFactory = await deployMaciFactory(deployer, 'medium')
Uncaught TypeError: Cannot read property 'batchUstVerifier' of undefined
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at deployMaciFactory (/Users/samrichards/code/ef/clrfund/contracts/utils/deployment.ts:43:94)
```

Looks like it's due to no `medium` option in `CIRCUITS`.

Just noting progress here... happy to make a PR to update that doc as things come up.

**Comment by samajammin** [comment]
Getting tripped up on the coordinator configuration:
https://github.com/ethereum/clrfund/blob/develop/docs/admin.md#configuration

What do you mean by a `serializedCoordinatorPubKey`? How should this be serialized?

I tried generating the public key using ethers.js:
```
const wallet = new ethers.Wallet(MY_PRIVATE_KEY)
const serializedCoordinatorPubKey = wallet.publicKey
```

But then I hit an error:
```
> const coordinatorPubKey = PubKey.unserialize(serializedCoordinatorPubKey)
Uncaught TypeError: Cannot read property 'length' of null
    at Function.PubKey.unserialize (/Users/samrichards/code/ef/clrfund/node_modules/maci-domainobjs/ts/index.ts:125:16)
    at new PubKey (/Users/samrichards/code/ef/clrfund/node_modules/maci-domainobjs/ts/index.ts:73:26)
```

**Comment by xuhcc** [comment]
@samajammin Coordinator key should be in MACI public key format: `macipk.1234...abcd`. You can generate one using MACI CLI. 

The coordination docs can be found here: https://github.com/clrfund/monorepo/blob/develop/docs/coordinator.md

**Comment by xuhcc** [comment]
There were plans to add key generation script to clrfund repo: https://github.com/clrfund/monorepo/issues/267#issuecomment-774717761

**Comment by xuhcc** [comment]
You can now generate MACI key by running `yarn workspace @clrfund/contracts ts-node scripts/generate-key.ts` (see #339)

**Comment by xuhcc** [comment]
@samajammin Did you succeed in deploying clrfund to testnet? I'll close this issue. Please reopen or create another issue if you have any more problems.

**Comment by samajammin** [comment]
> @samajammin Did you succeed in deploying clrfund to testnet? 

Unfortunately not yet, I got hung up on the MACI steps. Thanks for creating the script!

You can keep this closed. I'll try again & reopen if I hit issues.
