### ISSUE TITLE
Add ability for owner to approve requests in optimistic recipient registry

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#344]
Currently there's no ability for the contract owner to approve recipients. The only way a recipient is added to the registry is:
1.  Someone creates a request via `addRecipient`
2. Wait until the challenge period passes
3. Someone calls `executeRequest` on the request

I think it'd be an improvement to give the ability for the owner to immediately approve requests & add recipients to the registry. A couple potential approaches:
1. Refactor `executeRequest` so that if it's called by the owner, the request can be added to the registry without the requirement that the challenge period is over
2. Add a new function, e.g. `approveRequest` that only the owner can call & can be executed at any time

**Comment by samajammin** [comment]
I'd be happy to take a swing at this. @xuhcc do you have any preference on approach here?

**Comment by xuhcc** [comment]
I would prefer approach (1)
