### ISSUE TITLE
Refactor dev deploy scripts to deploy registries based on ENV variable

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#346]
In the frontend app we have a convenient ENV variable so we know which user & recipient registries to interact with. e.g. https://github.com/clrfund/monorepo/blob/develop/vue-app/.env.example#L14

It'd be great to add flexibility to our Hardhat deploy scripts to deploy the corresponding registries based on the same / similar ENV variable. Currently it always deploys the simple user & recipient registry:
https://github.com/clrfund/monorepo/blob/develop/contracts/scripts/deploy.ts#L30

**Comment by xuhcc** [comment]
I have a copy of deployments scripts that deploy optimistic registry instead of simple. I will get it finished and publish it.

**Comment by xuhcc** [comment]
@samajammin  #347
