### ISSUE TITLE
Rich, editable recipient profiles

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#35]

**Comment by xuhcc** [comment]
Currently recipient details in Kleros TCR can not be edited, but recipients can be removed and added again with different data.
In the future we may load recipient details from ENS where they can be easily updated. Relevant forum thread: https://forum.clr.fund/t/lets-talk-about-recipient-curation-mechanisms/15/20

**Comment by auryn-macmillan** [comment]
Closing because this has gone stale.
