### ISSUE TITLE
Persist wallet connection on page refresh

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#350]
Currently if a user is connected to the app with MetaMask & they refresh the page, the connection is lost (they must reconnect). A nice UX win would be to keep the user's wallet connect on page refresh.

I've seen other dapps in the space achieve this, e.g. https://app.uniswap.org/

At this moment I'm not sure what the technical solution is. I'll update here as I learn more.

**Comment by samajammin** [comment]
Ok so I think this can be achieved by reconnecting to the last connected provider upon page load, which could stored as a reference in `localStorage`. Some libraries provide this out of the box, e.g.:
- https://github.com/NoahZinsmeister/web3-react
- https://github.com/web3modal/web3modal

**Comment by samajammin** [comment]
If we go with the approach to solve using e.g. https://github.com/web3modal/web3modal, perhaps this could be solved in tandem with #349

**Comment by xuhcc** [comment]
>Currently if a user is connected to the app with MetaMask & they refresh the page, the connection is lost (they must reconnect)

No, the connection is not lost. But user needs to provide a signature which is used to decrypt MACI keys and other stuff.

**Comment by samajammin** [comment]
> No, the connection is not lost. But user needs to provide a signature which is used to decrypt MACI keys and other stuff.

Ahhh, interesting. So the Metamask is still connected, but the user must sign a message for MACI? The UI makes it seem like the wallet is disconnected (by no longer showing the address & instead showing the "connect" button) - is that intentional?

If that's the case, is that necessary for us to do this whenever a user refreshes the page? To ask a different way - why is the signature needed? If it's only needed to contribute/re-allocate, I'd suggest we only do that then. e.g. if I'm a recipient applying via the optimistic registry, do I need to connect to MACI at all? If not, I don't think we should force this signature for all users in order to "connect".

**Comment by xuhcc** [comment]
As I said, the signature is needed to decrypt user data. It is required for all contributor actions. It is not required for recipient registration but I don't think there should be an exception just for that case.
