### ISSUE TITLE
Upgrade Hardhat version

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#355]
Hey @xuhcc - I just tried upgrading the Hardhat version (to v2.2.1) so that we can configure delays in block times (to test out UI states for pending txs):
- https://medium.com/nomic-labs-blog/increased-mining-flexibility-in-hardhat-network-1fa2707ebd38
- https://hardhat.org/hardhat-network/#mining-modes

After upgrading, `yarn start:node` works but `yarn start:dev` yields this error with MACI:

```
$ yarn start:dev
yarn run v1.19.1
$ yarn deploy:local && yarn start:web
$ yarn workspace @clrfund/contracts run deploy:local && yarn workspace @clrfund/contracts run deployTestRound:local
$ yarn clean && yarn build && hardhat run --network localhost scripts/deploy.ts
$ rm -rf cache && rm -rf build
$ hardhat compile
Compiling 40 files with 0.6.12
Compilation finished successfully
Factory deployed: 0x5FC8d32690cc91D4c39d9d3abcBD16989F875707
$ hardhat run --network localhost scripts/deployTestRound.ts
Token deployed: 0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e
Funding round deployed: 0x0000000000000000000000000000000000000000
Error: call revert exception (method="maci()", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.0.9)
    at Logger.makeError (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
    at Logger.throwError (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
    at Interface.decodeFunctionResult (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/abi/src.ts/interface.ts:326:23)
    at Contract.<anonymous> (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/contracts/src.ts/index.ts:309:44)
    at step (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/contracts/lib/index.js:46:23)
    at Object.next (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/contracts/lib/index.js:27:53)
    at fulfilled (/Users/samrichards/code/ef/clrfund/contracts/node_modules/@ethersproject/contracts/lib/index.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'maci()',
  errorSignature: null,
  errorArgs: [ null ],
  address: '0x0000000000000000000000000000000000000000',
  args: [],
  transaction: {
    data: '0x34a0922c',
    to: '0x0000000000000000000000000000000000000000',
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  }
}
error Command failed with exit code 1.
```

Any idea what's going on here? Thanks in advance!

**Comment by samajammin** [comment]
Created a repro of this error, see https://github.com/clrfund/monorepo/pull/356

**Comment by xuhcc** [comment]
>Funding round deployed: 0x0000000000000000000000000000000000000000

It looks like the `FundingRound` deployment transaction was not mined.

**Comment by samajammin** [comment]
> It looks like the FundingRound deployment transaction was not mined.

Good point @xuhcc. It appears the interval mining is creating issues with the deploy scripts. I asked about this in the Hardhat Discord & they gave me some direction. Noting here to return to this soon:

> Hey Sam, if you enable interval mining, your deploy scripts indeed might stop working. I think the fix is something like this (assuming you are using ethers.js):

```
// convert this
const foo = await Foo.deploy()
await foo.deployed()

// into this
const foo = await Foo.deploy()
await foo.deployTransaction.wait()
```
> Honestly, I would expect those two statements to be equivalent, but they are not for some reason
And obviously this will make your deploys slower

> If what you want is to simulate more realistic scenarios in a frontend, an alternative would be to have automine enabled in your config and then do this:
```
// deploy stuff with automine enabled

await network.provider.send("evm_setAutomine", [false])
await network.provider.send("evm_setIntervalMining", [500])
```

I think the latter approach sounds like our best bet: 
- have automine enabled in the config by default
- create a standalone script/task to enable interval mining for the situations we want to test that out

**Comment by xuhcc** [comment]
>await foo.deployTransaction.wait()

Does this fix the problem?

**Comment by auryn-macmillan** [comment]
Closing as this issue is stale.
