### ISSUE TITLE
Use mastercopy-proxy pattern for all factory contracts

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#359]
Currently, the `FundingRoundFactory` deploys a new instance of `FundingRound` for each new round (which also deploys an instance of MACI). This transaction costs ~10,000,000 gas.

We can dramatically reduce this gas cost by implementing a pattern similar to the Gnosis Safe's mastercopy-proxy pattern, where each version of the contracts has a reference deployment and any [factory contracts deploy proxies](https://github.com/gnosis/safe-contracts/tree/main/contracts/proxies) that make delegate calls to those reference deployments.

This will enable:
1. Deployments that are orders of magnitude cheaper
2. Persistent addresses for FundingRoundFactory contracts (they can be upgraded between rounds, no need to redeploy)
3. Anyone to [replay the deployment](https://github.com/gnosis/safe-contract-deployment-replay) of the reference implementations of the contracts to any network.

**Comment by auryn-macmillan** [comment]
@daodesigner, @viraj124 is keen to take on this issue. Just wanted to touch base with you on it since it will likely impact (and may have already been addressed by) your work on the deployer.

**Comment by daodesigner** [comment]
That would be great, should be a drop in replacement on the deployer side, so this would be a great first issue to tackle. Let's coordinate to use the same contracts for subgraph registration/agree on an ABI.

**Comment by viraj124** [comment]
Thanks @daodesigner Will coordinate with you when I start

**Comment by daodesigner** [comment]
For reference here are the current deploy costs for each of the contracts after compiler optimization. 
*note: the deployNewRound contract call deploys `FundingRound`/`MACI` contracts.

```
Contract deployment: MACIFactory
Gas used:            5,178,462 

Contract deployment: FundingRoundFactory
Gas used:            4,555,109 

Contract deployment: OptimisticRecipientRegistry
Gas used:            1,591,758 

Contract deployment: BrightIdUserRegistry
Gas used:            702,831 

Contract call:       FundingRoundFactory#deployNewRound
Gas used:            7,749,574 
```

**Comment by viraj124** [comment]
@daodesigner I will probably start on this on weekend will keep you posted
Thanks

**Comment by viraj124** [comment]
@daodesigner currently deployment takes place via a function as you said so you expect this behavior to remain the same so it does not affect the current deployment flow ?
asking since the proxy pattern deployment architecture is different from the current architecture, I am thinking of using create2 like used here https://github.com/gnosis/safe-contracts/blob/main/contracts/proxies/GnosisSafeProxyFactory.sol#L61 still have to figure out the flow but goof to get these discussions started early

**Comment by daodesigner** [comment]
If you have to change the function signature or architecture that’s fine, just justify your changes as comments and make sure all the tests still pass and the scripts still work 😄

**Comment by Tranvanlap95** [comment]
0xe4e834fc6808181668501E89a85F1cC40ad941d9
