### ISSUE TITLE
Upgrade to MACI 0.9

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#366]
A new version of MACI will be released in the coming days. Before launching the next round, we should go ahead and update.

**Comment by auryn-macmillan** [comment]
MACI 0.9.1 was just released
https://www.npmjs.com/package/maci-crypto

**Comment by daodesigner** [comment]
* going with [0.9.2](https://github.com/appliedzkp/maci/releases/tag/v0.9.2) thanks to  @weijiekoh who was able to shave off 1M gas on new round deployment costs with some quick thinking.

- [x] Increase solc optimizer runs for Libraries
- [x] Benchmark gas costs for major operations using new Circuits
- [x] All Contracts under 24kb size limit
- [x] All Contracts deploys under gasLimit
- [x] All Tests passing
- [ ] Deploy new Libraries to xDAI
- [x] Parameters for new Trusted Ceremony on IPFS
- [ ] Confirm Coordinator PubKey
- [ ] Admin set new MACI Params on Funding Factory Contract
- [ ] Deploy new round

**Comment by weijiekoh** [comment]
BTW the param files I sent to @auryn-macmillan a few days ago will work with 0.9.2 too.

**Comment by auryn-macmillan** [comment]
> BTW the param files I sent to @auryn-macmillan a few days ago will work with 0.9.2 too.

I went ahead and [pinned them on IPFS](https://gateway.pinata.cloud/ipfs/QmWSxPBNYDtsK23KwYdMtcDaJg3gWS3LBsqMnENrVG6nmc).

**Comment by daodesigner** [comment]
For posterity: using MACI 0.9.4 (thank you @weijiekoh), the pinned contracts, and some solc compiler optimization, these are the current contract sizes, luckily these circuits should scale well into the millions of users. 

![image](https://user-images.githubusercontent.com/58278045/125000872-5cc5b180-e01f-11eb-8b45-6457c94627d3.png)
