### ISSUE TITLE
Nested clr.fund instances?

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#38]
Recipient projects may belong to categories with distinct characteristics that would be best funded by distinct clr.fund instances. For example:
1. Project teams of certain categories may have a more (or less) direct relationship with the individuals their project benefits, creating distinct dynamics relating to projects ability to attract contributions. See the media section of Gitcoin Grants.
2. Groups of projects may have such different purposes as to dilute the schelling point of a shared funding pool, which could hurt the pool's ability to attract marginal contributors or matching funds.

**So we should just have separate funds, right?**
We probably should. But doing so comes with some decentralization and credible neutrality challenges. Once categories are defined, filtering recipients into categories isn't a problem: recipients can self-select into categories, and contributors can police that self-selection with their contribution choices (e.g. "don't fund a media project in the tech category"). The bigger issue is with deciding what the categories should be.

Who gets to make that decision? And who decides how matching funds get allocated to each category? Gitcoin Grants, for example, decided a few rounds ago to separate Media and Tech projects into their own categories. This was probably the right decision given how much of a fundraising / shilling advantage the top media projects have over everything else (see example 1 above), but should we be ok with one or two people unilaterally making that decision? If we're trying to build a credibly neutral fundraising platform, the answer is No.

**So what can we do?**
Instead of a few people making the decision, we can let the community decide what the categories should be and how much funding they get. We already have a great mechanism to do this: clr.fund itself!

The idea is to nest instances of clr.fund within other instances, creating a multi-level hierarchy of instances:
- The highest level (L0) has one instance of clr.fund and is responsible for selecting and allocating funds to each category of projects. Example categories -- "Ethereum Protocol-Level Development," "Ethereum Application-Layer Development," "Ethereum Media"
- The lowest level (Ln) has many instances of clr.fund: one for each category identified in higher levels. Each instance is responsible for selecting and allocating funds to individual recipient projects within the given category. Example recipients w/in "Ethereum Protocol-Level Development" -- "Prysmatic," "Optimism," "OpenEthereum"
- Each category receiving funds from a given instance triggers a new instance for the next round at the next level down. The total funds allocated to that category in the initial round become the matching funds in the next round.
- There can be any number of intermediate levels (e.g. L1, L2, where sub-categories and sub-sub-categories can be selected and funded. For example, "Ethereum Protocol-Level Development" could be further split into layer 1, layer 2, ETH2, ETH1.x or any number of variations.
- All of these levels are established organically. There's no requirement that a given instance be for categories or for projects. Categories and instances can be proposed and compete for funds within the same instance / level!
- Contributors of both matching funds and matched funds can contribute at any level. For example, if I care about advancements in layer 2 scaling in general but am not sure which projects are most deserving, I can contribute to the layer 2 category within the "Ethereum Protocol-Level Development" instance. My funds then become part of the matching funds for layer 2 projects.

**Comment by auryn-macmillan** [comment]
Closing this for now. Will explore it again at some point.
