### ISSUE TITLE
Deps issues when running scripts with the trusted setup files

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#417]
This is not a blocker for us but we wanted to mention that I've been trying to run the `genProofs` using the trusted setup files (https://gateway.pinata.cloud/ipfs/QmWSxPBNYDtsK23KwYdMtcDaJg3gWS3LBsqMnENrVG6nmc) but I had the following error:
```
0 / 2
0 / 6
Writing MaciState to macistate
Generating proofs of message processing...

Progress: 1 / 1; batch index: 0
genBatchUpdateStateTreeCircuitInputs() took 2.546 seconds
batchProcessMessage() took 0.981 seconds
/maci/circuits/params/batchUst32: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /maci/circuits/params/batchUst32)
Error: unable to compute batch update state tree witness data
Error: exec: /maci/circuits/params/batchUst32: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /maci/circuits/params/batchUst32)

    at Object.error (/maci/circuits/node_modules/shelljs/src/common.js:110:27)
    at execSync (/maci/circuits/node_modules/shelljs/src/exec.js:102:12)
    at Object._exec (/maci/circuits/node_modules/shelljs/src/exec.js:205:12)
    at Object.exec (/maci/circuits/node_modules/shelljs/src/common.js:335:23)
    at /maci/circuits/ts/index.ts:230:11
    at step (/maci/circuits/build/index.js:33:23)
    at Object.next (/maci/circuits/build/index.js:14:53)
    at /maci/circuits/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/maci/circuits/build/index.js:4:12)
```

I have tested this against:
- a local HH instance, running the scripts using:
	- Ubuntu 19.10
	- Ubuntu 19.10 host + Docker image running node:15.8.0-buster
- a RinkArby instance, running the scripts using:
	- Ubuntu 19.10
	- Ubuntu 19.10 host + Docker image running node:15.8.0-buster
	- Ubuntu 19.10 host + Docker image running node:14.18-bullseye (expecting an upgrade on `libc.so.6`)

***
Aside from that, using my own params files, they worked as expected in all the mentioned envs.

Wondering what env are you guys using to run the MACI scripts @daodesigner @auryn-macmillan

**Comment by daodesigner** [comment]
@pettinarip you are going to need to use Ubuntu 21.04^ as your server image- or recompile the binaries on your machine using the param files and your libc version (this is why the other param files do work on your machine).

Unfortunately the binaries pinned on IPFS were compiled using a higher version of libc (2.3.3) than is available on the Ubuntu version you are using.

Feel free to ping me if you need any help!

**Comment by pettinarip** [comment]
Perfect @daodesigner. Yes, I recall Weijei telling me that he had used Ubuntu 21.04 as well. Ok, when I can, I'll try to run it with an ubuntu image. Thanks!

**Comment by pettinarip** [comment]
@daodesigner just to confirm that it worked with docker using ubuntu 21.04 + node 15 🎉

**Comment by daodesigner** [comment]
Awesome! Please add a note to the docs, we should probably bump the version of Ubuntu on the Docker image as well.

**Comment by pettinarip** [comment]
> Awesome! Please add a note to the docs, we should probably bump the version of Ubuntu on the Docker image as well.

Cool. I've created a PR to use ubuntu in the Docker image here: https://github.com/appliedzkp/maci/pull/337

Will add a note in our docs soon.
