### ISSUE TITLE
Enable matching funds and contributions to use two different ERC20 tokens

### ISSUE THREAD

**Issue by johnson86tw** [clrfund/monorepo#429]
If a DAO has their own governance token and would like to run clr.fund instance in the community, it makes sense that they would choose to use the token as a kind of voice credit to vote on the instance.

As for matching funds, they’re probably another ERC20 token or stable coins from the outside of DAO. So the DAO can set up an instance and make collective decisions in the community for the allocation of that external sources.

**Comment by daodesigner** [comment]
Not possible in 0.10.X will reopen after MACI 1.0 integration
