### ISSUE TITLE
Project cards with different width

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#435]
When the cart panel is closed we have the following width size:
![1](https://user-images.githubusercontent.com/468158/134977352-053b2fc3-97de-4bdf-ba12-5358d2762971.png)

But when the cart is opened, it is bigger:
![2](https://user-images.githubusercontent.com/468158/134977359-b8b99c39-cdca-4960-8267-26b7c1cdc91f.png)

To fix this issue I think we will need to change the layout of the Cart container. Probably, we would need to position it as absolute in order to have it "floating" on top of the content of the page. This way, the Project List width is not going to change when the Cart is opened or closed.

Not sure if I'm clear. What do you think? is it worth the effort?

**Comment by auryn-macmillan** [comment]
The current behaviour seems fine, tbh.
