### ISSUE TITLE
Add banner/disclaimer to project page if it's too late to contribute

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#437]
[MIGRATED ISSUE FROM https://github.com/ethereum/clrfund/issues/313]

Realizing it's potentially not obvious to visit a project page & understand that it's too late for contributions.

e.g. check out https://eth2clrfund.netlify.app/#/project/0xed608bf9be5dc545096b9bfa5ea1932268eb80718360f9c887750a54606a9e2a

![clr fund - Commons Simulator 2021-08-27 at 4 21 05 PM](https://user-images.githubusercontent.com/8097623/131197587-47a1efa3-a407-46cc-8c63-2007accb7f4c.jpg)

Particularly applicable when on mobile & you can't see the round info on the sidebar. On mobile we also display the "Add to cart" input (although it _is_ disabled):
![clr fund - Commons Simulator 2021-08-27 at 4 22 07 PM](https://user-images.githubusercontent.com/8097623/131197620-ab2e9091-76b0-4d48-a7de-96d2cab7ab5a.jpg)

If projects are promoting their individual pages (e.g. on Twitter), it's likely to be common for visitors to land on a project page. I think we should make it more obvious by e.g. displaying a disclaimer that the project is not in an active round.

Should we also hide the mobile cart input if the round is closed?

One example to look at is Gitcoin grants, e.g. https://gitcoin.co/grants/2141/beacon-book
They display a "Not in an active matching round" header before the "About" section of the project.

**Comment by auryn-macmillan** [comment]
Closing as this issue appears to have been fixed.
