### ISSUE TITLE
Make verification check more clear

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#438]
[ THIS IS A MIGRATED ISSUE - ORIGINAL: https://github.com/ethereum/clrfund/issues/330 ]

Just walked through the verification flow, which involved clicking "Check if you are verified" to view my BrightID verification status:

https://user-images.githubusercontent.com/8097623/131523338-cb4ca481-50aa-46e6-b26a-11239101c3c4.mp4

I don't think this UX is currently clear that the check is working. It flashes so quickly that it seems like it might be a bug.

Perhaps we can add additional text or refresh the "Unverified" text e.g. with a CSS animation to show that we did successfully complete a check & the result is that they're still not yet verified.

**Comment by auryn-macmillan** [comment]
Related to #506
