### ISSUE TITLE
Layout bug on Join form

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#439]
MIGRATED ISSUE FROM: https://github.com/ethereum/clrfund/issues/371

![image](https://user-images.githubusercontent.com/54227730/133289781-4ae5cb7a-19a1-4e4b-8242-0c847638967b.png)

Noticed this on `develop` branch when going to the `Join` form

**Comment by auryn-macmillan** [comment]
Seems to have gone stale.
