### ISSUE TITLE
Project profile page - elements cut off when user is connected

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#442]
ISSUE MIGRATED FROM https://github.com/ethereum/clrfund/issues/336

e.g. https://eth2clrfund.netlify.app/#/project/0x6c75b81beafbfa711563c4e49ab0f247573cde594ea7cf0aea08fab2035e08e6

When I'm not connected, all looks good:
![clr fund - Corwintines staking pool 2021-09-01 at 11 59 06 AM](https://user-images.githubusercontent.com/8097623/131728512-4e437eb8-e37c-4c4c-a4e2-0eb41fd4b471.jpg)

But once I connect the sidebar of the cart cuts off the cart input & links section:
![clr fund - Corwintines staking pool 2021-09-01 at 11 59 32 AM](https://user-images.githubusercontent.com/8097623/131728616-2f4d72cc-6cd8-4020-813c-624a3953ade4.jpg)

Also when cart is open it nearly cuts it off:
![clr fund - Corwintines staking pool 2021-09-01 at 11 59 39 AM](https://user-images.githubusercontent.com/8097623/131728739-ec34a154-99e6-4b83-86a2-687733592136.jpg)

(Brave on MacBook Air)

**Comment by pettinarip** [comment]
These pages also look messy on mobile (Safari iPhone X):

![image](https://user-images.githubusercontent.com/8097623/131729142-30576d56-4d1d-45cf-b4ae-cece19bdb5b6.png)

![image](https://user-images.githubusercontent.com/8097623/131729129-4c69f206-abc5-4076-a3f0-6c5b0ba5b004.png)

**Comment by auryn-macmillan** [comment]
This issue seems to be stale.
