### ISSUE TITLE
Account for 0 DAI balance

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#444]
ISSUE MIGRATED FROM: https://github.com/ethereum/clrfund/issues/322

When trying to contribute to the matching pool:

![image](https://user-images.githubusercontent.com/468158/150360678-b1239b76-440c-497d-a264-610c666db985.png)

If balance is 0 we should say something along the lines of "You don't have any DAI on this account".

Note - once we have the resource built, we should add a link that explains how to get (L2) DAI, e.g. by using Uniswap.

**Comment by auryn-macmillan** [comment]
What about something like this? `"You do not have enough {token}. Your balance is {balance} {token}"`

**Comment by auryn-macmillan** [comment]
We're going to leave this as is for now. The current error message seems fine.
