### ISSUE TITLE
Potentially confusing location of "Submit" button for new receipients

### ISSUE THREAD

**Issue by pettinarip** [clrfund/monorepo#445]
ISSUE MIGRATED FROM: https://github.com/ethereum/clrfund/issues/240

![image](https://user-images.githubusercontent.com/54227730/128442582-a2ce8f2a-2f9f-4274-8b4d-a345fadefe06.png)

Was suggested through user feedback that after the entire `Join` form flow has the "continue" button in the same place, but the final step to submit moves the button to the middle. 

Filing here for discussion.

**Comment by auryn-macmillan** [comment]
On the "submit" step, we should remove the current "Submit Project" button and instead just use the "continue" button that was present in the previous steps to trigger the transaction that "Submit Project" does in the current design.
