### ISSUE TITLE
Can't claim after round ends

### ISSUE THREAD

**Issue by crisgarner** [clrfund/monorepo#454]
After a round ends, the UI says that I need to head to my project profile to claim the funds. No button appears to claim the funds. Using Gnosis Safe and wallet connect as the recipient is a multi-sig.
![Screenshot from 2022-02-06 18-41-27](https://user-images.githubusercontent.com/578688/152709170-a942d708-64e3-4edf-aec1-e954319dd218.png)
![Screenshot from 2022-02-06 18-41-22](https://user-images.githubusercontent.com/578688/152709173-49c2a770-9f35-4cc8-adc6-9f371375cd00.png)
![Screenshot from 2022-02-06 18-41-17](https://user-images.githubusercontent.com/578688/152709174-89236d0a-14bf-4330-95d0-31a817afb2ea.png)

**Comment by samajammin** [comment]
Hmmm @pettinarip any idea what the issue might be here?

@crisgarner is appears the wallet you're connected with is the same as the recipient address to claim the funds, correct?

**Comment by samajammin** [comment]
@daodesigner if you're able to share the ENV variables related to this round, we could run this in our local dev & try to debug. I suspect it has to do with the logic/data around displaying the claim button: https://github.com/clrfund/monorepo/blob/develop/vue-app/src/components/ClaimButton.vue#L101

Feel free to ping @pettinarip or I on TG 😄

**Comment by daodesigner** [comment]
Hey this was actually resolved already will close the issue now. Turns out
was just the IPFS file with tally data was not pinned.
