### ISSUE TITLE
Factory Contract: Cancelling the funding round

### ISSUE THREAD

**Issue by xuhcc** [clrfund/monorepo#46]
If coordinator is changed by owner during the funding round, the round must be cancelled.

All funds from the pool must be transferred to the new round:

https://github.com/clrfund/monorepo/blob/3273baf760c9aec9d3d2f96bc51731150e8e8b0e/contracts/contracts/FundingRoundFactory.sol#L160-L161

**Comment by xuhcc** [comment]
This is tricky.
When round is being cancelled, it's not just the money that must move to the next contract, but also the data on who contributed and what amount. I see two possible solutions:

1. We iterate on the list of contributors in the cancelled round and re-register each one of them in the next round contract. This could be done in batches, but it's still expensive.
2. We put the responsibility for transferring funds onto the contributors. They will be allowed to withdraw funds from the cancelled round and then they could contribute these funds in the next round.

I would prefer option 2 as it makes the system more autonomous (less dependent on us), but option 1 may seem better in terms of UX.

**Comment by auryn-macmillan** [comment]
I'd be ok with option two as well, since users will have to resubmit their votes to MACI anyway.
