### ISSUE TITLE
Project profile page: images in project description overflows cart widget

### ISSUE THREAD

**Issue by samajammin** [clrfund/monorepo#488]
Noticed in the current EthStaker round, e.g. this project:
https://qf.ethstaker.cc/#/project/0x572aa97f1650464f819d90151c48f21f3d34bef9e3a015e70018b25e6c4d3d29

It likely depends on screen size but at 1280 width, the wide images in the description completely pushes the cart widget off screen:
<img width="1280" alt="Screen Shot 2022-05-08 at 8 23 50 PM" src="https://user-images.githubusercontent.com/8097623/167309999-c1499d55-340b-4a14-8aeb-a4d24d98181a.png">

I'm also not able to horizontally scroll in order to view that content...

Only by zooming out to 75% can I see the whole cart & links widget:
<img width="1280" alt="Screen Shot 2022-05-08 at 8 25 10 PM" src="https://user-images.githubusercontent.com/8097623/167310084-af9941e2-1383-406e-8e4d-278d8c2c6a92.png">

I think we should restrict the size of these uploaded images to make sure they don't exceed a certain width.

**Comment by samajammin** [comment]
@pettinarip could you please look into this?

**Comment by pettinarip** [comment]
@samajammin I think the issue is related to the `grid` layout we have. Let me look into this but I think we don't need to touch the image constraints.

**Comment by auryn-macmillan** [comment]
Fixed
