### ISSUE TITLE
Need an array of recipients corresponding the the vote options in MACI

### ISSUE THREAD

**Issue by auryn-macmillan** [clrfund/monorepo#51]
https://github.com/clrfund/monorepo/blob/4e6e6e9ed13dbd58856328bb5cbfd08d8313a518/contracts/contracts/FundingRoundFactory.sol#L25

Votes in MACI are cast for an index, rather than a specific address. So we need an array of addresses that corresponds to the vote options in MACI.

Here is an example of how we might build such an array, along with a mapping for convenient two-way lookup.
https://github.com/clrfund/registry/blob/master/contracts/Registry.sol

**Comment by xuhcc** [comment]
Duplicate of #19

**Comment by auryn-macmillan** [comment]
So it is! I'll close this one.
