### ISSUE TITLE
Factory contract: Add recipients with metadata

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#57]
For Round 0, recipients will be added to the round along with their metadata. The address will be stored in the contract and the metadata will be emitted with an event.

- [FundingRoundFactory.addRecipients()](https://github.com/clrfund/monorepo/blob/8f4977a2713e787047141a628201443217e41894/contracts/contracts/FundingRoundFactory.sol#L68) emits an event that includes whatever metadata we want (address, name, URL, description, profile image, everest id?, other stuff?)

**Comment by xuhcc** [comment]
In the beginning we will need project name, description and an IPFS hash of an image:

![Screenshot_2020-08-04 Figma](https://user-images.githubusercontent.com/1660460/89265539-52e04500-d63d-11ea-8f2c-1cfbd838ec0c.png)
