### ISSUE TITLE
separate `contribute()` function into two functions: `contribute()` and `addMessages()`

### ISSUE THREAD

**Issue by adamstallard** [clrfund/monorepo#9]
The current[ `contribute()` function in FundingRound.sol](https://github.com/clr-fund/contracts/blob/master/contracts/FundingRound.sol#L51) allows a user to add to their total contribution for the round; it also allows them to add messages for MACI (prepared commands for directing votes and changing the signing key).

A user may want to do these separately.

**Comment by xuhcc** [comment]
Implemented in #69
